runtime: python311
instance_class: F2

env_variables:
  FLASK_APP: "wsgi.py"
  FLASK_ENV: "production"

handlers:
- url: /static
  static_dir: app/static
  secure: always

- url: /.*
  script: auto
  secure: always
