services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"    environment:
      - DATABASE_URL=postgresql://postgres:y3WhoYFS@db/barberia_db
      - SECRET_KEY=y3WhoYFS
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=pipevale2011@gmail.com
      - MAIL_PASSWORD=kotu kfnc eakg ypqt
      - MAIL_DEFAULT_SENDER=Barber Brothers
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=y3WhoYFS
      - POSTGRES_DB=barberia_db
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=y3WhoYFS
      - POSTGRES_DB=barberia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
