"""agregar campo descripcion a modelo de barbero

Revision ID: 3841bdb9e5a7
Revises: 80c7f3f85c2c
Create Date: 2025-04-28 10:23:10.882195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3841bdb9e5a7'
down_revision = '80c7f3f85c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbero', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
