"""crear tabla productos

Revision ID: 38cfef5f337c
Revises: a894756db028
Create Date: 2025-04-25 16:31:28.225928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38cfef5f337c'
down_revision = 'a894756db028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('producto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('imagen_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('creado', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='producto_pkey')
    )
    op.drop_table('productos')
    # ### end Alembic commands ###
