"""add servicio imagenes table

Revision ID: 6365f72a12fc
Revises: b5c13252ebef
Create Date: 2025-06-13 09:44:08.285305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6365f72a12fc'
down_revision = 'b5c13252ebef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicio_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('ruta_imagen', sa.String(length=255), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicio_imagenes')
    # ### end Alembic commands ###
