"""nuevas funcionalidades barbero

Revision ID: 72e2e3648da8
Revises: dc20d04d2287
Create Date: 2025-08-23 14:52:32.587118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e2e3648da8'
down_revision = 'dc20d04d2287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueo_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbero_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbero_id'], ['barbero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bloqueo_horario')
    # ### end Alembic commands ###
