"""actualizaciones de cita

Revision ID: 80c7f3f85c2c
Revises: 38cfef5f337c
Create Date: 2025-04-27 10:28:33.565795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c7f3f85c2c'
down_revision = '38cfef5f337c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disponibilidad_barbero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbero_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['barbero_id'], ['barbero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_column('duracion')

    op.drop_table('disponibilidad_barbero')
    # ### end Alembic commands ###
