"""añadir relacion servicio a citas

Revision ID: 8e0fcda9f1f0
Revises: f6a003b8ac25
Create Date: 2025-05-03 10:33:13.495442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0fcda9f1f0'
down_revision = 'f6a003b8ac25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('barbero_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('servicio',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('servicio_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('servicio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('servicio',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('barbero_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
