"""empty message

Revision ID: a78c6e6f92f8
Revises: 72e2e3648da8
Create Date: 2026-01-17 11:21:33.660280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78c6e6f92f8'
down_revision = '72e2e3648da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbero_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbero_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('precio_personalizado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbero_id'], ['barbero.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbero_id', 'servicio_id', name='uq_barbero_servicio')
    )
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_cobrado', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('es_precio_personalizado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_column('es_precio_personalizado')
        batch_op.drop_column('precio_cobrado')

    op.drop_table('barbero_servicio')
    # ### end Alembic commands ###
