"""añadir_campos_segmentacion_clientes

Revision ID: b5c13252ebef
Revises: d9ab714dfe0f
Create Date: 2025-05-19 15:07:30.675416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c13252ebef'
down_revision = 'd9ab714dfe0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_visita', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_visitas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('segmento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fuente_captacion', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('fuente_captacion')
        batch_op.drop_column('segmento')
        batch_op.drop_column('total_visitas')
        batch_op.drop_column('ultima_visita')

    # ### end Alembic commands ###
