"""se añadio un modelo para categoria

Revision ID: cb20c1fe267d
Revises: cbbb32890a54
Create Date: 2025-05-07 16:43:53.637744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb20c1fe267d'
down_revision = 'cbbb32890a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_column('servicio')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id'])
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.drop_table('categorias')
    # ### end Alembic commands ###
