"""añador campo cantidad a producto

Revision ID: d9ab714dfe0f
Revises: 2f13a7d796f5
Create Date: 2025-05-15 10:04:12.280270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ab714dfe0f'
down_revision = '2f13a7d796f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
