"""Cambios al apartado de servicios

Revision ID: dc20d04d2287
Revises: eedc9969b49f
Create Date: 2025-07-17 15:28:12.254343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc20d04d2287'
down_revision = 'eedc9969b49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_servicio_orden'), ['orden'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicio_orden'))
        batch_op.drop_column('orden')

    # ### end Alembic commands ###
