"""agregar_tabla_sliders

Revision ID: eedc9969b49f
Revises: 4c2c061b1ee9
Create Date: 2025-06-19 14:28:12.527299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedc9969b49f'
down_revision = '4c2c061b1ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sliders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('subtitulo', sa.String(length=300), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_embed_code', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sliders')
    # ### end Alembic commands ###
