"""añadir relacion servicio a citas

Revision ID: f6a003b8ac25
Revises: 3841bdb9e5a7
Create Date: 2025-05-03 08:26:17.794124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a003b8ac25'
down_revision = '3841bdb9e5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'servicio', ['servicio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notas')
        batch_op.drop_column('servicio_id')

    # ### end Alembic commands ###
