name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Para poder ejecutar manualmente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        zip -r deploy.zip . -x "*.git*" -x "*.github*" -x "*__pycache__*" -x "*.pyc" -x "instance/*" -x "logs/*"
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'barberia-app'  # Reemplaza con el nombre de tu App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy.zip
        
    - name: Post-deployment setup
      run: |
        echo "Running database setup and migrations..."
        curl -X POST "https://barberia-app.azurewebsites.net/api/health" || echo "Health check may have failed, but continuing..."
