name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-azure.txt
        
    - name: Run tests if present
      run: |
        if [ -d "tests" ]; then
          echo "Running tests..."
          pytest tests/
        else
          echo "No tests directory found, skipping tests"
        fi
      continue-on-error: true
      
    - name: Optimize static assets
      run: |
        # Comprimir imágenes si tienes herramientas instaladas
        echo "Optimizing static assets..."
        find app/static -type f -name "*.jpg" -o -name "*.png" | xargs -r echo "Would compress:"
      continue-on-error: true
      
    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        zip -r deploy.zip . -x "*.git*" -x "*.github*" -x "*.pytest_cache*" -x "*__pycache__*" -x "*.pyc"
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'barberia-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy.zip
        
    - name: Warm up application
      run: |
        echo "Warming up application..."
        curl -sS https://barberia-app.azurewebsites.net/api/health || echo "Health check failed, but continuing"
