name: Deploy to Azure App Service (F1 - Economic)

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Para poder ejecutar manualmente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-minimal.txt  # Usar versión mínima para reducir tamaño
        
    - name: Prepare for deployment
      run: |
        # Asegurar que los scripts tengan permisos de ejecución
        chmod +x startup-azure.sh
        chmod +x setup_db_azure.py
        chmod +x build.sh
        
        # Crear estructura de directorios necesaria
        mkdir -p app/static/uploads
        mkdir -p logs
        
        # Crear deployment package
        echo "Creating deployment package..."
        zip -r deploy.zip . -x "*.git*" -x "*.github*" -x "*__pycache__*" -x "*.pyc" -x "instance/*" -x "migrations/versions/*" -x "logs/*" -x "*.md" -x "cloud-sql-proxy.exe" -x "debug_images.py" -x "add_categories.py"
      # OPCIÓN 1: Usar AZURE_WEBAPP_PUBLISH_PROFILE (método recomendado)
    - name: Deploy to Azure Web App con Publish Profile
      id: deploy-to-webapp-profile
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'barberia-app'
        slot-name: 'production'
        package: ./deploy.zip
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      
    # OPCIÓN 2: Usar AZURE_CREDENTIALS con SERVICE_PRINCIPAL (alternativa)
    # Descomenta esta sección y comenta la sección anterior si prefieres este método
    # - name: Login to Azure
    #   uses: azure/login@v1
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
    #
    # - name: Deploy to Azure Web App
    #   id: deploy-to-webapp
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'barberia-app'
    #     slot-name: 'production'
    #     package: ./deploy.zip
        
    # Run initial setup if needed
    - name: Run post-deployment script
      run: |
        echo "Esperando a que la aplicación se inicie..."
        sleep 30
        
        # Intentar ejecutar un health check
        curl -s "https://barberia-app.azurewebsites.net/api/health" || echo "Health check no disponible, pero continuando..."
